DROP PROCEDURE IF EXISTS sp_create_pengguna;
CREATE PROCEDURE sp_create_pengguna(
    IN p_nama VARCHAR(255),
    IN p_email VARCHAR(255),
    IN p_password VARCHAR(255),
    IN p_peran ENUM('owner', 'admin', 'petugas', 'anggota'),
    IN p_telepon VARCHAR(255),
    IN p_alamat TEXT,
    IN p_foto_profil VARCHAR(255)
)
BEGIN
    -- ID is generated by Trigger tr_pengguna_id_insert
    INSERT INTO pengguna (
        nama, email, password, peran, telepon, alamat, 
        foto_profil, status, created_at, updated_at
    ) VALUES (
        p_nama, p_email, p_password, p_peran, p_telepon, p_alamat, 
        p_foto_profil, 'aktif', NOW(), NOW()
    );
END;

DROP PROCEDURE IF EXISTS sp_update_pengguna;
CREATE PROCEDURE sp_update_pengguna(
    IN p_id_pengguna VARCHAR(20),
    IN p_nama VARCHAR(255),
    IN p_email VARCHAR(255),
    IN p_password VARCHAR(255),
    IN p_peran ENUM('owner', 'admin', 'petugas', 'anggota'),
    IN p_telepon VARCHAR(255),
    IN p_alamat TEXT,
    IN p_status ENUM('aktif', 'nonaktif'),
    IN p_foto_profil VARCHAR(255)
)
BEGIN
    UPDATE pengguna
    SET 
        nama = p_nama,
        email = p_email,
        password = IF(p_password IS NOT NULL AND p_password != '', p_password, password),
        peran = p_peran,
        telepon = p_telepon,
        alamat = p_alamat,
        status = p_status,
        foto_profil = IF(p_foto_profil IS NOT NULL, p_foto_profil, foto_profil),
        updated_at = NOW()
    WHERE id_pengguna = p_id_pengguna;
END;

DROP PROCEDURE IF EXISTS sp_delete_pengguna;
CREATE PROCEDURE sp_delete_pengguna(
    IN p_id_pengguna VARCHAR(20)
)
BEGIN
    DELETE FROM pengguna WHERE id_pengguna = p_id_pengguna;
END;
